### ISSUE TITLE
wordfish and ca C++ code not linking

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.textmodels#1]
(Should install **quanteda** from the `no-textmodels` branch first.)

Looks like some problem with macro expansion in the function name.

```r
> example("textmodel_wordfish")

txtmd_> (tmod1 <- textmodel_wordfish(data_dfm_lbgexample, dir = c(1,5)))
 Error in .Call("_quanteda_textmodels_qatd_cpp_wordfish_dense", PACKAGE = "quanteda.textmodels",  : 
  "_quanteda_textmodels_qatd_cpp_wordfish_dense" not available for .Call() for package "quanteda.textmodels" 
```

@koheiw can you take a look and fix?

**Comment by koheiw** [comment]
I think you need this somewhere to link C++ files. We have this in `quanteda-documentation.R`.
```r
#' @useDynLib quanteda, .registration = TRUE
```
I often forget this...
