### ISSUE TITLE
probability of the word given the class (empirical likelihood)

### ISSUE THREAD

**Issue by mavino** [quanteda/quanteda.textmodels#53]
Following tutorial at https://content-analysis-with-r.com/5-machine_learning.html, I came across the function textmodel_nb and I want to retrieve the PwGc. It used to be model.NB$PwGc if model.NB is my trained model. However i am not able to retrieve those with the new version of  textmodel_nb(), can you help me, please. Thank you very much!

**Comment by cschwem2er** [comment]
You can find P(W)|P(C) within `model$param` and P(C) within `model$priors`. Is this really would you want though, or are you missing P(C|W), which was available in earlier versions of `textmodel_nb`?

I tried to reconstruct P(C|W), but am not sure whether I have done it correctly. Could @kbenoit or @koheiw please take a look ? (Also, I think it would be nice to have PcGw as a returned value)

````
get_pcgw <- function(nb_model) {
  norm_cols <- function(x) {
    x / outer(rep(1, nrow(x)), colSums(x))
  }
  pwgc <- nb_model$param
  pc <- outer(nb_model$priors, rep(1, ncol(pwgc)))
  pcgw <- norm_cols(pwgc * pc) 
  return(pcgw)
}

library(quanteda)
library(quanteda.textmodels)
txt <- c(d1 = "Chinese Beijing Chinese",
         d2 = "Chinese Chinese Shanghai",
         d3 = "Chinese Macao",
         d4 = "Tokyo Japan Chinese",
         d5 = "Chinese Chinese Chinese Tokyo Japan")
x <- dfm(tokens(txt), tolower = FALSE)
y <- factor(c("Y", "Y", "Y", "N", NA), ordered = TRUE)
tmod1 <- textmodel_nb(x, y, prior = "docfreq")

get_pcgw(tmod1)

    Chinese   Beijing  Shanghai     Macao     Tokyo     Japan
N 0.1473684 0.2058824 0.2058824 0.2058824 0.5090909 0.5090909
Y 0.8526316 0.7941176 0.7941176 0.7941176 0.4909091 0.4909091
````

**Comment by kbenoit** [comment]
I think `coef()` also can extract these.
